version: "3.8"
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=dental
            - POSTGRES_PASSWORD=dental
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    postgres:
